name:                fizzbuzz
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/fizzbuzz#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs:        src

#executables:
#  fizzbuzz-exe:
#    source-dirs:      src
#    main:             Main.hs

tests:
  fizzbuzz-test:
    main:             Spec.hs
    source-dirs:      test
    dependencies:
      - fizzbuzz
      - hspec
      - QuickCheck
